### ISSUE TITLE
Can't update visualization options after the first render

### ISSUE THREAD

**Issue by drosen0** [forio/contour#195]
Once a chart is rendered once, you can't change a visualization's options prior to re-rendering.

The options get overwritten in [contour.js line 360](https://github.com/forio/contour/blob/master/src/scripts/core/contour.js#L360)

``` js
var opt = _.merge({}, this.options, visualization.options);
```

which is designed to allow the visualization-specific options (ie. `.line(data, options)`) override the Contour options (`new Contour(options)`).

As an example, render a line chart

``` js
var chart = new Contour({
    el: '#vis'
})
.cartesian()
.line(data)
.render();
```

then change the animationDirection of the line

``` js
chart.options.line.animationDirection = 'bottom-to-top';
```

and re-render with updated data

``` js
chart.setData(data).render();
```

The animation is still left-to-right.

It works if you set

``` js
chart._visualizations[0].options.line.animationDirection = 'bottom-to-top';
```

but that's a temporary workaround.

**Comment by drosen0** [comment]
Slightly better workaround is
```
chart.select(0).options.line.animationDirection = 'bottom-to-top';
```

**Comment by narenranjit** [comment]
More relevant conversations for context:

----

naren shouldn't
``` this.contourInstance.options.xAxis.title = newValue;
          this.contourInstance.options.chart.animations.enable = false;
          this.contourInstance.render();```
update the title and not re-animate the line series? (edited)
or am i mis-interpreting how that works?
(i see the title change but it still animates)

drosen I think the option has already been copied to the line visualization instance by this point, so unfortunately you have to do a hack

naren what's the hack?
the line doesn't take an animate property does it?

drosen well I looked and the line visualization reads the chart’s options, so it should work

naren doing 'this.contourInstance.options.chart.animations.duration = 0' kinda sorta fixed it
it still animates the markers however :-/

drosen maybe give this a try:
```this.contourInstance._visualizations[0].options.animations.enable = false;
```

naren i don't know at this point how many visualizations are there though -- is just looping through `_visualizations` the same thing?

or does _visualizations also include axes etc?

drosen it’ll include line and tooltip but I don’t think axes are in there

naren markers?

drosen markers are part of line

naren that should be fine then, thanks

drosen it’s a hacky solution though

naren yeah, i'll file an issue on the contour github abt it
maybe a `contourinstance.options({..} )` is called for

drosen that might be a good solution. Ideally the options passed into the visualization wouldn’t be a deep clone, but if I remember correctly, Jaime had a reason for it

drosen well, there’s `Contour#select(index)` which returns `_visualizations[index]`, but you’d still need to get the length of `_visualizations` or keep incrementing `index` until it returns `undefined`

naren the lack of the leading underscore makes me feel better already

drosen or, there’s `Contour#composeOptions()` which appears to copy the options to the visualizations, but possibly might overwrite things you don’t want to overwrite

**Comment by drosen0** [comment]
Oh, silly me, there's `VisInstanceContainer#setOptions(options)`, which you would use as:
```js
chart.select(0).setOptions({ line: { animationDirection: 'bottom-to-top' } });
```
This does does not seem to be documented anywhere. It should probably be documented near http://forio.com/contour/documentation.html#contour -> `Contour#select()`.

**Comment by mmrj** [comment]
@drosen0 added to the list for next docs updates, thanks

**Comment by narenranjit** [comment]
Options can now can in functions, and there's a separate updateOptions method. this is now redundant
