### ISSUE TITLE
element.offsetParent does not work in firefox

### ISSUE THREAD

**Issue by buchowski** [forio/contour#212]
domHelpers.getStyle & domHelpers.getCentroid use element.offsetParent, but offsetParent isn't supported for SVGs in Firefox. 

This breaks tooltips on Pie Charts.

**Comment by mmrj** [comment]
verified in local build of 0.9.117+this fix.
 - in regular 0.9.117, no tooltips in firefox
 - in 0.9.117+this fix, tooltips in firefox match those in chrome
