### ISSUE TITLE
Overlapping tooltip selects wrong data even if element hidden. 

### ISSUE THREAD

**Issue by senluchen2015** [forio/contour#221]
Problem: Currently if there are two overlapping points, the first tooltip will always be selected even if it is hidden.  
In tooltip.js, the function show is: 

``` javascript
var show = function (d) {
    clearHideTimer.call(this);

    var dataPoints = findOriginalDataPoint(d);

   /**line 140**/ this.tooltipElement.select('.text').html(getTooltipText.call(this, dataPoints[0] || d, dataPoints));

    var pos = positionTooltip.call(this, d);

    this.tooltipElement
        .style('top', pos.y + 'px')
        .style('left', pos.x + 'px');

    changeOpacity.call(this, this.options.tooltip.opacity, this.options.tooltip.showTime);
};
```

I believe that on line 140, dataPoints[0] || d is overriding the data and only picking the first in the set since || will always pick the first point: 

``` javascript
this.tooltipElement.select('.text').html(getTooltipText.call(this, dataPoints[0] || d, dataPoints));
```

Switching the order of the || works for the project I'm working on with overlapping points.

``` javascript
this.tooltipElement.select('.text').html(getTooltipText.call(this, d || dataPoints[0], dataPoints));
```

However, I am wondering what findOriginalDatPoint(d) is suppose to do. It seems to select all data with  the same x and y as the parameter's and then the html text is based on the first one (dataPoints[0]). Can someone confirm if this is the case and if switching the order makes sense?

``` javascript
function findOriginalDataPoint(d) {
    var res = [];
    _.each(data, function(series, seriesIndex) {
        var name = series.name;
        _.each(series.data, function(point) {
            if (point.x === d.x && d.y === point.y) {
                res.push(_.extend(point, {
                    series: name,
                    seriesIndex: seriesIndex
                }));
            }
        });
    });
    return res;
}
```

**Comment by drosen0** [comment]
I believe the intent of `findOriginalDataPoint()` is to make tooltips consistent, so that the lowest-index series at a point is the first one for which a formatter is attempted to be found.

By using a custom formatter specified in `options.tooltip.formatter`, you can choose which of the overlapping data points to display in the tooltip.

```js
new Contour({
    el: '.myChart',
    tooltip: {
        formatter: function (d, allPoints) {
            return _.map(allPoints, function (p) {
                return p.series + ': ' + p.x + ', ' + p.y;
            }).join('<br>');
        }
    }
})
    .cartesian()
    .line([2, 4, 3, 5, 7])
    .tooltip()
    .render();
```

Therefore I don't believe this is a bug.

**Comment by drosen0** [comment]
Reopening because we determined it's a bug in Contour. Need to evaluate just a little more.

**Comment by narenranjit** [comment]
See also https://issues.forio.com/browse/VALUEPROP-88

**Comment by senluchen2015** [comment]
Here's a fiddle showing the problem. 
http://jsfiddle.net/vz0czzbb/
In this graph the Math line is hidden through css (display: none) but if you hover over the second Economics point it would be the tooltip for the Math line, because the point overlap.
See https://github.com/forio/contour/pull/223 for fix
