### ISSUE TITLE
Add caveat that setting yAxis max doesn't actually mean that's the max.

### ISSUE THREAD

**Issue by narenranjit** [forio/contour#231]
Customer complaint. They set max for chart to 1.5M, but the actual graph showed 2M. I believe this is due to the nicing, but we should document that and suggest how they can try different number of y-axis-ticks to make it look closer to what they want. 

(assuming you can't turn off nicing. if you can we should document that instead)

**Comment by drosen0** [comment]
Interestingly, there's a broken link to [nicing](http://forio.com/contour/documentation.html#core_config/config.yAxis.nicing) in the docs for [smartAxis](http://forio.com/contour/documentation.html#core_config/config.yAxis.smartAxis)

**Comment by ldtcooper** [comment]
This no longer appears to be an issue. Additionally, the nicing probl was reported and fixed as part of issue 278.
