### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by narenranjit** [forio/contour#242]
The tests are initially written in jasmine 1.x and don't work with jasmine 2.x. To fix we should either (in order of preference/difficulty)

- Hardcode a jasmine 1.x dependency in package.json (not sure why we moved to 2 since it doesn't work?)
- Change to mocha; a quick glance through the tests indicate it's not too dissimilar and since we have more internal mocha knowledge it'll be an easier migration.
- Update tests to jasmine 2.0

**Comment by parikhshiv** [comment]
Looked into this - I'm able to run these tests in the browser, so I'm thinking it's possible that we may have already updated our tests to jasmine 2.0, and just did not delete the comment in our Gruntfile that says we need to upgrade our tests. 

It's also possible that this may be a PhantomJS issue - I'll explore further.

**Comment by parikhshiv** [comment]
Tests are running correctly with jasmine 2.0, so I'm closing this issue - I've deleted the comment indicating that tests are out of date in PR #247.

**Comment by mmrj** [comment]
marking verified per @parikhshiv 's comment
