### ISSUE TITLE
'height' property leaks from one contour call to another

### ISSUE THREAD

**Issue by wglasshusain** [forio/contour#245]
I made a custom "donut" graph, incorrectly leaving out the height property.  The graph defaulted to a height of 30 which looked bad.  Eventually I figured out how to add chart.height property and it worked.  But -- that's not this ticket.

The ticket is in reference to my discovery that the height property can leak from a previous call to Contour to the new one.  Specifically, the code in block [1] below has the default (too-small) height of 30.   But if I add another unrelated Contour call before it, e.g. block [2] it has the previously specified height of 170.

Here's an example of code that doesn't work.  Note the two examples need div tags "pie-chart" and "results-chart".  

  ```
    var formatter = d3.format('%');
    Contour.export('donutTextOneValue', function (data, layer, options) {

        var visibleIndex = data[0].data[0].y < data[0].data[1].y ? 1 : 0;
        var centerX = options.chart.plotWidth / 2;
        var centerY = options.chart.plotHeight / 2;
        var progressPercentage = data[0].data[0].y;
        console.log('dd = ', progressPercentage)

        layer.append('text')
            .attr('class', 'center-text')
            .attr('x', centerX - 18)
            .attr('y', centerY)
            .attr('dy', '.3em')
            .text(progressPercentage + '%');

    });

    var data = [93,7];
    new Contour({
            el: '.pie-gauge',
            pie: {
                innerRadius: 30
            }
        })
        .pie(data)
        .donutTextOneValue(data)
        .render();
```

If you preceed it with this empty graph the donut graph also picks up the height of 170.

   ```
 // displays graph with no data
    new Contour({
            el: '.results-chart',
            chart: {
                height: 170
            }
        })
    .cartesian()
    .render();
```

**Comment by mmrj** [comment]
from @wglasshusain : "it's not leaking in javascript.  it has to do with the surrounding div tag.  it takes that height by default.  so if it gets larger than the height gets larger.   that's how one graph affected the other."

**Comment by wglasshusain** [comment]
Molly beat me to it.   I spent more time testing this.   As she notes, the leakage was via CSS and not unreasonable.  I think one graph made the row taller which increased the height for the graph.
