### ISSUE TITLE
Question: Is this project under active development?

### ISSUE THREAD

**Issue by ndabAP** [forio/contour#255]
Hi! I may use this for a new project and would like to know if there are any future plans for this project. Thanks!

**Comment by narenranjit** [comment]
Hi @ndabAP  - Contour will be maintained, but we won't be aggressively adding a lot of new features in the short-term. We're actively using it in a few dozen projects every year and it currently meets most of our use-cases as-is, but we do plan to a new version by the end of the year with a few enhancements. 

We will take PRs however (maybe checkin with us on what you're planning in advance of making one however)

**Comment by ndabAP** [comment]
Great, thanks for the clarification.
