### ISSUE TITLE
Need vertical mark lines to axis

### ISSUE THREAD

**Issue by breadbaker** [forio/contour#259]
<img width="635" alt="screen shot 2017-11-08 at 8 26 41 am" src="https://user-images.githubusercontent.com/711512/32551476-a445fa14-c45e-11e7-9158-b4f0ff32bebe.png">

My designer wants vertical lines running through the point.  That display with the tooltip as shown in the screenshot.  Is this functionality possible?

**Comment by narenranjit** [comment]
http://jsfiddle.net/zecmfgj7/8/ has similar functionality
