### ISSUE TITLE
Y-Axis has difficulty detecting variations in small numbers (or small numbers in general?)

### ISSUE THREAD

**Issue by lukwallace** [forio/contour#280]
For small data sets, the yAxis does not set up ticks or plot data appropriately. Fighting w/ the config to get the data plotted will not provide desired ticks unless `tickValues` is explicitly set. I set up a fiddle w/ all the odd quirks that came out.

**Understandably, docs do say that axis will only scale to 1, 2, 5, 10 and 10x.**

Workarounds:
* Explicitly set `tickValues`
* multiply your data set on render; and use a yAxis formatter/tooltip formatter to divide

See: http://jsfiddle.net/p7n3fgej/

**Comment by ldtcooper** [comment]
This is a repeat of [issue 256](https://github.com/forio/contour/issues/256)
